// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TemuCerita - Admin Dashboard",
  description: "Admin dashboard for TemuCerita",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-emerald-50">
          <header className="bg-emerald-100 py-4 px-6 sticky top-0 z-50 shadow-md">
            <h1 className="text-2xl font-bold text-gray-900">TemuCerita</h1>
          </header>

          <div className="flex flex-col md:flex-row">
            <div className="w-full md:w-64 bg-emerald-700">
              <div className="md:fixed md:h-screen md:w-64">
                <div className="h-full">
                  {/* SideMenu will be rendered client-side */}
                  <div id="sidemenu-container" className="h-full" />
                </div>
              </div>
            </div>
            <div className="flex-1 p-6">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
